### ISSUE TITLE
Proposal to merge wwm into twm

### ISSUE THREAD

**Issue by TimUntersberger** [SirWindfield/twm#4]
Hey!

I feel like your project has a way better structure than wwm and I don't think that wwm will have a future without a major refactor, that's why I wanted to ask whether I can help you in any way to implement twm?

Merge might be the wrong word here, but I am willing to implement features that I have already implemented in wwm in twm (which might reduce the time required for a MVP state of twm). 

**My goal is to archive wwm and just port all of the important bits to twm.** 

I'm definitely excited to see the source code of twm-main!

**Comment by SirWindfield** [comment]
Hey!

Cool that you found the time around to take a look at my approach ^.^
Your idea sounds reasonable. I do have a lot more code lying around but am currently learning for some exams. I will push the rest of the code at the end of this month.

The cool thing about my approach is that the actual platform-dependent code is just one single function:
```
fn render_tile(tile: Tile) -> Result<...>;
```

As all information about position and size is calculated inside of `core`, I could extract the `winapi` calls to only rely on one `SetWindowPos`. That doesn't include keyboard shortcut hooks and stuff though :smile:

Keep an eye on the repository to see when I push the rest of the project ;)

I do have a lot more ideas about the project and will write a proper readme when I have time to do so. I especially want to get into why I decided to structure the project as it is of now!

**Comment by TimUntersberger** [comment]
> The cool thing about my approach is that the actual platform-dependent code is just one single function

> That doesn't include keyboard shortcut hooks and stuff though

How would you then handle windows that get opened? Do you already have an idea in mind?

Also would it be possible to implement a "ManualLayout" with the current structure? I looked at the pushed implementations and these two look more like a dwm.

One of the key things that makes twm a lot better than wwm is that you implemented the main code as a windows service. When I started with my approach I didn't even know what existed so I sadly went with the naive way. I'm very excited about being able to support software that has admin privileges.

If it is not too much to ask could you push the code already? I'm very excited to study your code and approach. If you would rather not do it then I'd be interested in why you are waiting to push to github (I usually just push everything right from the beginning)?

> I do have a lot more code lying around but am currently learning for some exams

Good luck for your exams!

**Comment by SirWindfield** [comment]
> How would you then handle windows that get opened? Do you already have an idea in mind?

The native functions are basically all abstracted away by a trait (as of now). In theory, one could even implement the thing in x11 if I didn't miss something.

> Also would it be possible to implement a "ManualLayout" with the current structure? I looked at the pushed implementations and these two look more like a dwm.

Do you mean something where you can move the tiles around and resize them? Yes, that is possible. I had a version were you could swap out tiles and resize them but the code did get lost during my refactoring as I deleted the wrong branch :(

> If it is not too much to ask could you push the code already? I'm very excited to study your code and approach. If you would rather not do it then I'd be interested in why you are waiting to push to github (I usually just push everything right from the beginning)?

I can, but it's super super ugly at the moment. It's not fully implemented either. It's just a main function that initializes anything but rendering isn't even completely added right now. The last thing I have implemented was the protocol, which ought to be a problem by itself as I had never worked with tokio. I am still debating on which framework to use for IPC. I do not want to spin some custom format into existence so I do think that JSON RPC is a ncie approach, but there are a handful of crates that I was testing to get a feel on how "good" they are in this use-case.

I can push to another branch. But there isn't really much right now. I sadly deleted the wrong branch some days ago and lost a good amount of work (which had the fully tray icon and windows service components implemented).

**Comment by SirWindfield** [comment]
The problem with the crate I use for RPC is that it relies on an old version of tokio that still uses futures-0.1.0 and not std::future. Total pain to work with. So I am still looking for a crate with real async support that is using std.

**Comment by TimUntersberger** [comment]
Thank you!

> I sadly deleted the wrong branch some days ago and lost a good amount of work (which had the fully tray icon and windows service components implemented).

If I remember correctly you can [recover the branch](https://stackoverflow.com/questions/3640764/can-i-recover-a-branch-after-its-deletion-in-git/22303923)

Is there a reason you didn't use the default implementation of the MSG struct [here](https://stackoverflow.com/questions/3640764/can-i-recover-a-branch-after-its-deletion-in-git/22303923) ?

> So I am still looking for a crate with real async support that is using std and allows communication through pipes or files.

I have never really used RPC before, so sorry if the question is stupid, but is the speed gain really that significant compared to something like a simple http server or something more on that level?

**Comment by SirWindfield** [comment]
> Edit: Just looked up RPC and I think my question above is completely stupid

;)

> Is there a reason you didn't use the default implementation of the MSG struct here?

Not sure what link you wanted to post but it is the same as before 🗡️ 

> I have never really used RPC before, so sorry if the question is stupid, but is the speed gain really that significant compared to something like a simple http server or something more on that level?

Probably not, no. But it feels cleaner to be honest. Piping is just nice to have IMO, but I will probably go for a HTTP server for now as there is more crates I can choose from. The second step would either be porting later on or implementing a Pipe wrapper for the crate we settle on.

> If I remember correctly you can recover the branch.

I did find the SO answer but it didn't work. Not sure why :( It's not a big problem. It was just an afternoon's worth of work, nothing major :smile:

**Comment by SirWindfield** [comment]
Ah ye, the reason why I wanted the ability to retrieve specific information in the first place, which resulted in RPC, is that programs like `polybar` can be used to fetch the information (which is returned as json), pipe it through `jq` to get only the stuff you want and pipe that into `polybar` to display the information. Sadly `polybar` is not for Windows but I had plans to implement a lightweight alternative for twm that works basically the same, where each "module" is a script that runs periodically.
